### ISSUE TITLE
"sudo phala score-test <parameter>" does not work

### ISSUE THREAD

**Issue by infrachris** [Phala-Network/solo-mining-scripts#16]
The command "sudo phala score-test 4" returns the output of "sudo phala help" below is a snippet:

_~# sudo phala score-test 4
Usage:
        phala [OPTION]...

Options:
        help                                    display help information
        install                                 install your phala node
                <dcap>                          install DCAP driver..._

**Comment by gregorst3** [comment]
https://github.com/Phala-Network/solo-mining-scripts/pull/18
