### ISSUE TITLE
Bug in sudo phala start - endless loop

### ISSUE THREAD

**Issue by michaelmowry** [Phala-Network/solo-mining-scripts#20]
When I run sudo phala start I get an endless loop that says the script has been automatically upgraded.

$ sudo phala start
----------The local script version is too low and has been automatically upgraded. Please execute the command again!----------
$ sudo phala start
----------The local script version is too low and has been automatically upgraded. Please execute the command again!----------
$ sudo phala start
----------The local script version is too low and has been automatically upgraded. Please execute the command again!----------

**Comment by zozyo** [comment]
en version of update.sh did not update version info in .env
