### ISSUE TITLE
Logic and labelling in sudo phala status

### ISSUE THREAD

**Issue by infrachris** [Phala-Network/solo-mining-scripts#24]
"khala chain synchronization status" appears to not actually show khala's chain data but is instead showing kusama's.  See the below example, according to this I have 8,876,624 blocks to go until khala will be sync'd "khala chain synchronization status" "Synchronizing, please wait, difference is 8876624".  8,876,624 is much larger than the entire block height of the khala chain, so it should be impossible to display a value so large as 8876624.  I believe this line in the status is actually a count down of how many blocks are left until kusama is sync'd.  Further, kusama chain sync status shows the difference is '0' however I know that kusama chain is not completely sync'd.

It may be worth noting in my particular case, khala-node container continuously crashes and is not running, which is likely an unrelated issue but worth mentioning.

------------------------------ Script version 0.1.6 ----------------------------
        service name            service status          local node block height
--------------------------------------------------------------------------
        khala-node              exited                   / 428696
        kusama-node             exited                   / 9305320
        phala-pruntime          running
        phala-pherry            running                 khala 0 / kusama 0
--------------------------------------------------------------------------
        Status check                                            result
--------------------------------------------------------------------------
        khala chain synchronization status              Synchronizing, please wait, difference is 8876624
        kusama chain synchronization status             Synchronization completed, difference is 0
        pherry synchronizes khala chain status          Synchronization completed, difference is 
        pherry syncs kusama chain status                Synchronization completed, difference is

**Comment by infrachris** [comment]
I believe this paradigm may only occur if the khala-node container is not running, perhaps just show a warning if that container is not running.

**Comment by h4x3rotab** [comment]
Thx. We will consider
