### ISSUE TITLE
bug in update.sh 

### ISSUE THREAD

**Issue by zozyo** [Phala-Network/solo-mining-scripts#26]
in function check_version()

if wget form github failed, the script will still rm files. ( whcih happens frequently in China )

in line 8, only check the version not equal, does not check if the tmp exist or not.

should check if wget success or not, if failed, retry 3 times then exit with error code.

https://github.com/Phala-Network/solo-mining-scripts/blob/bd7d335454cbdde9e10476fce094801fe8e9927b/scripts/cn/update.sh#L8

**Comment by skysummerice** [comment]
We have fixed this issues. Thanks.
