### ISSUE TITLE
Getting error when running any phala commands

### ISSUE THREAD

**Issue by gngchrs** [Phala-Network/solo-mining-scripts#35]
Hello, 
I keep getting this error when I run any phala commands
```
/usr/bin/phala: line 75: syntax error near unexpected token `}'
/usr/bin/phala: line 75: `}'
```

**Comment by hauni97** [comment]
@gngchrs Thank you for letting us know. We are aware of this issue and working on a fix. We apologize for the inconvenience.

**Comment by hauni97** [comment]
This should be solved since 12/01/2021. If it persist please reinstall your scripts.
