### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/solo-mining-scripts#39]
1. Use `rm -rf ...` instead of `echo yes | rm -r ...`
2. Specify the full path in deleting script section (should we use `sudo rm -rf $HOME/solo-mining-scripts-main`?)
3. Deleting the database
    - To delete Khala, just run `rm -rf /var/khala-dev-node/chains/khala`. No need to delete the three directories separately
    - Add: to delete Kusama blockchain ,run `rm -rf /var/khala-dev-node/chains/polkadot`

**Comment by hauni97** [comment]
@h4x3rotab  
Done! See here: https://github.com/Phala-Network/solo-mining-scripts/commit/72777a5540a3560b95491e893c949f4671169b1c

However `sudo rm -rf $HOME/solo-mining-scripts-main` does not work if home is `/root`.

Here my suggested solution:

```bash
home_path=eval echo ~$USER
$home_path
sudo rm -rf sudo rm -rf
```

**Comment by h4x3rotab** [comment]
I didn't understand. If you are already log on as root, you can right execute `rm -rf $HOME/solo-mining-scripts-main`

If you are in another user, you need to switch to root anyway. Then you can run something like `sudo rm -rf /root/solo-mining-scripts-main`.

The above code is really weird. What's `sudo rm -rf sudo rm -rf`? Are you going to remove a file called "sudo" under the current directory?

**Comment by h4x3rotab** [comment]
Also, we have to ensure all the code change is reviewed. Do not commit directly to the main branch.

**Comment by hauni97** [comment]
> 

Yes, indeed. This is obviously wrong what was committed. It was supposed to be:
```bash
home_path=`eval echo ~$USER`
$home_path
sudo rm -rf /$home_path/solo-mining-scripts-main
```

However, I'd suggest to edit to:

To find your home directory where `solo-mining-scripts-main` should reside execute: 
```bash
eval echo ~$USER
```

To then delete it execute:
```bash
sudo rm -rf /insert_your_path_from_previous_command/solo-mining-scripts-main
```

**Comment by hauni97** [comment]
@h4x3rotab can we close this issue?

**Comment by h4x3rotab** [comment]
OK. Sounds good
