### ISSUE TITLE
Snapshot header mismatch

### ISSUE THREAD

**Issue by terminalsin** [Phala-Network/solo-mining-scripts#65]
Reported by RHO#0136

![image](https://user-images.githubusercontent.com/30368557/191832331-23150ab3-efce-4c3e-84a9-d63dcbcac9ff.png)

- Updating does not solve said issue
- Script is up to date

**Comment by skysummerice** [comment]
HI terminalsin
Thanks for your report, we have use a wrong hash for this file.
Now we fixed it.

**Comment by skysummerice** [comment]
fixed
